### ISSUE TITLE
Devel test blocks forever

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#80]

**Comment by WyseNynja** [comment]
I'm almost done changing the http/ws provider split. After that, fix this test. It broke because it sees that the rpc is only a block behind and is willing to wait for it. But in the test, the blocks never advance. This will be easily fixed by adding a `select` where the consensus head connection change is awaited and adding a simple timeout

**Comment by WyseNynja** [comment]
fixed in b1a0bcac575542aea3c11f413ba88dd0d877e46e
